services:
  backend:
    build: ./backend       
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - static:/backend/static
      - media:/backend/media

  frontend:
    build: ./frontend 
    restart: unless-stopped
    expose:
      - 3000
    command: serve -s /frontend/build -l 3000
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/backend/static
      - media:/backend/media
    depends_on:
      - frontend

volumes:
  static:
    external: false
  media:
    external: false 